### ISSUE TITLE
About the Figma API

### ISSUE THREAD

**Issue by opcodewriter** [evanw/kiwi#23]
@evanw As a continuation of https://github.com/evanw/kiwi/issues/17 I'd like to share some thoughts about what you mentioned:

> I just asked because if you are parsing raw Figma files, you should know that this is our internal format which is not intended to be stable. Our HTTP API and our plugin API are the things we intend to be stable. 

I totally understand your idea of having a public API which encapsulates and which gives you the flexibility to change how things work in the actual Figma format. But, having to call the Figma web API has several cons:

- Client relies on Figma servers. What happens when it hits the Figma API limits? 
   This is a serious limitation, albeit I've no idea how easy or hard it is to hit those limits...
- Client has to be online

> For example, an alternative approach could be to create a Figma plugin to export to PSD

Yes but that has its own limitations in how the plugin (which is a web app basically) can communicate to the outer world (which is only by a web communication)

Looking forward to hear your thoughts..

**Comment by evanw** [comment]
I completely understand why it would be convenient for Figma to have a purely client-side library for parsing Figma files. However, that goes against our goals of ecosystem stability. We want integrations with Figma to be set up for success by default, and a purely client-side library does not do this. We deliberately do not document our internal format because we don't want people to use it and then have their integration with Figma inevitably break in the future.

We have at least one project in the works as we speak that changes the file format in substantial ways that may break existing clients relying on the internal format. And in the future there's a good chance that we will completely rewrite the file format to improve performance. It's not good for our users if third-party integrations with Figma break periodically, and we try to make decisions to ensure that the ecosystem is stable, at least to the best of our ability.

You are of course free to attempt to consume Figma files anyway, as Photopea has done. But that workflow is not one we currently support, and so will not be documented. Doing this means you take full responsibility for staying on top of undocumented and unannounced changes to our internal data structures, as well as for any potential future breakage with whatever you are building.

**Comment by opcodewriter** [comment]
> 
> 
> I completely understand why it would be convenient for Figma to have a purely client-side library for parsing Figma files. However, that goes against our goals of ecosystem stability. We want integrations with Figma to be set up for success by default, and a purely client-side library does not do this. We deliberately do not document our internal format because we don't want people to use it and then have their integration with Figma inevitably break in the future.
> 
> We have at least one project in the works as we speak that changes the file format in substantial ways that may break existing clients relying on the internal format. And in the future there's a good chance that we will completely rewrite the file format to improve performance. It's not good for our users if third-party integrations with Figma break periodically, and we try to make decisions to ensure that the ecosystem is stable, at least to the best of our ability.
> 
> You are of course free to attempt to consume Figma files anyway, as Photopea has done. But that workflow is not one we currently support, and so will not be documented. Doing this means you take full responsibility for staying on top of undocumented and unannounced changes to our internal data structures, as well as for any potential future breakage with whatever you are building.

How about having at least a library (any programming language will do) which can parse the format? 
I think you already have it internally, so it would be a matter to expose it. 

Even if the API of this library still change, that would be OK for any third party, because parsing the Figma file is itself an internal implementation of a third party tool, they will adapt to the changes.

I think exposing a library has benefits for you too, because it will cut down a lot of traffic to your servers.

**Comment by opcodewriter** [comment]
I updated my message above, in case you read the message by email.

**Comment by mostafaznv** [comment]
I want to convert `json` response from api to `.fig` file. is there any chance to tell me how I can do it? 😁

**Comment by yagudaev** [comment]
@mostafaznv I'm working on it now. Already have reading/writing .fig files working https://github.com/yagudaev/figma-to-json

Hope it helps 😁

**Comment by mostafaznv** [comment]
> @mostafaznv I'm working on it now. Already have reading/writing .fig files working https://github.com/yagudaev/figma-to-json
> 
> Hope it helps 😁

Thanks for the suggestion. but I want to convert json to .fig file. your tool does the opposite

**Comment by mostafaznv** [comment]
> @mostafaznv I'm working on it now. Already have reading/writing .fig files working https://github.com/yagudaev/figma-to-json
> 
> Hope it helps 😁

Thanks for your nice tool.
Is there any way to use this tool standalone? as a command-line tool or something else?

**Comment by yagudaev** [comment]
@mostafaznv not at the moment, but shouldn't be too hard to change it to do that. How were you thinking of using it? Cron job type?

**Comment by mostafaznv** [comment]
> @mostafaznv not at the moment, but shouldn't be too hard to change it to do that. How were you thinking of using it? Cron job type?

Yes. I want to create a job to backup all my projects everyday and store them in a secure sever.
