### ISSUE TITLE
Has there been any change in the compression data part of the .fig file?

### ISSUE THREAD

**Issue by Deeby** [evanw/kiwi#43]
I am working on a Python program to read and analyze the canvas.fig file inside a Figma file. 
For some reason, although reading and analyzing the schema part works fine, I am encountering an issue with decompressing the data section of the file.

I have the following code for decompression:
   data = zlib.decompress(data_block, wbits=-zlib.MAX_WBITS)

The file structure is as follows:
12 bytes (header)
4 bytes (schema length)
[zlib compressed schema data]
4 bytes (data length)
[zlib compressed data]   <=== ### Here, can not decompress

Everything seemed fine with previous versions of the .fig files, but recently created .fig files fail to decompress the zlib compressed data.

Is there something I might be doing wrong, or has there been a change in the compression method or format for recent versions of the .fig files?

I apologize for not finding a more suitable place to ask this question.

**Comment by evanw** [comment]
I'm closing this issue because this applies to Figma files, not the kiwi message encoding. I do not work at Figma and haven't worked their for many years now. Figma may have switched to zstd compression for their file format given that https://github.com/figma/zstddec exists. I recommend trying that decompression library instead on the compressed data.

**Comment by Deeby** [comment]
After applying the method you suggested, it worked perfectly. Thank you so much! I'm really happy to have learned something new.
